### ISSUE TITLE
Wrong implementation of the algorithm?

### ISSUE THREAD

**Issue by amuradyan** [Chalyan/physics-applied-problems#2]
https://github.com/Chalyan/matlab_substitutor/blob/20fb45e93b15229237c706b93149396c71b51802/1.1_Linear_equations_numerical_method.py#L15-L28

Aren't we overriding the `x2` from line 17 here? This means that the `x2` that went into the calculation of `x1` on line 24 is different from the one that goes into the `x3` calculation two steps later.

Is this the expected behavior?

I updated the code to use different names /see #1/ and get the following results when I run the original and updated code with these parameters **[`x1`: 1, `x2`: 4, `x3`: 3, `epsilon`: 8]**

original code:   [ 2, 0.75,  -1.775]
updated code:  [ 2, 1, -3.1]

**Comment by Chalyan** [comment]
While writing the code, the mentioned above case was not taken into consideration, because the meaning of epsilion and initial values are respectively the maximum difference between values of `Xi` in consecutive iterations and a random initial values for linear equation solutions before iterations and it is promised to converge anyways :)
But thanks for collaboration and the newly opened PR ✨️

And yes, it is way more beautiful now, than it was before 😁

**Comment by Chalyan** [comment]
Later the implementation will be modified in terms of a rank of matrix, because the existing veraion only works for 3×3 matrices.
